name: CMake

on:
  push:
    branches:
      - master
      - 'release-*'
  pull_request:
  # run on all pr

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        shared: ["ON", "OFF"]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - shared=${{ matrix.shared }}

    steps:
    - uses: actions/checkout@v2

    - name: Create build dir
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: |
        cmake .. -DBUILD_SHARED_LIBS=${{ matrix.shared }} -DUTF8PROC_ENABLE_TESTING=ON
        cmake --build .

    - name: Run Test
      working-directory: ${{github.workspace}}/build
      run: ctest
